spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/cadastro
    password: Sen@c2023
    username: postgres
    driverClassName: org.postgresql.Driver